// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByBGInag_XDkeZc8nCq1DRdx3yizQO-2s',
    appId: '1:528569998198:web:f99384c8d7ff9c8b163857',
    messagingSenderId: '528569998198',
    projectId: 'flutter-2f441',
    authDomain: 'flutter-2f441.firebaseapp.com',
    storageBucket: 'flutter-2f441.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcWd8GSaabgeEPhdSfSpkBEo4H9DJIBTw',
    appId: '1:528569998198:android:b35e94b1c7166994163857',
    messagingSenderId: '528569998198',
    projectId: 'flutter-2f441',
    storageBucket: 'flutter-2f441.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtCsEFjwrWpuqKEAC1VPKp5d4idOk9SpA',
    appId: '1:528569998198:ios:9fdb7b2e6ed807c3163857',
    messagingSenderId: '528569998198',
    projectId: 'flutter-2f441',
    storageBucket: 'flutter-2f441.appspot.com',
    iosBundleId: 'com.example.figmatoflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtCsEFjwrWpuqKEAC1VPKp5d4idOk9SpA',
    appId: '1:528569998198:ios:61dc69d33b9daf40163857',
    messagingSenderId: '528569998198',
    projectId: 'flutter-2f441',
    storageBucket: 'flutter-2f441.appspot.com',
    iosBundleId: 'com.example.figmatoflutter.RunnerTests',
  );
}
