name: Flutter Web
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.1
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release --base-href /pet_app/
      - run: |
          cd build/web
          git init
          # type configurations: your user.email and user.name followed lines 
          git config --global user.email g060606770@gmail.com
          git config --global user.name Xiang
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/Xiang329/pet_app.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
